# Generated by Django 4.0.2 on 2022-02-14 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_films', '0003_film_watched_alter_film_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='ttcode',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='IMDB Code'),
        ),
    ]
