# Generated by Django 4.0.2 on 2022-02-16 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('top_films', '0005_alter_person_options_alter_film_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_films', models.ManyToManyField(related_name='favorited_by', to='top_films.Film')),
                ('films_to_watch', models.ManyToManyField(related_name='on_watchlist_of', to='top_films.Film')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='top_films.forumuser'),
            preserve_default=False,
        ),
    ]
