# Generated by Django 4.0.2 on 2022-02-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_films', '0006_forumuser_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
